In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/raw/goodreadss_books.csv")

print(f"Shape: {df.shape[0]:,} righe × {df.shape[1]} colonne\n")

print("Prime righe del dataset:")
print(df.head())

print("Descrizione categorie numeriche:")
display(df.describe())

print("Descrizione categorie numeriche:")
display(df.describe(include=['object', 'category']))

missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing_Count': missing,
    'Missing_%': missing_pct.round(2)
}).sort_values('Missing_Count', ascending=False)
print(missing_df)
print(f"\n Valori mancanti: {missing.sum()} ({missing.sum()/len(df)*100:.2f}%)")

Shape: 20,068 righe × 24 colonne

Prime righe del dataset:
   Unnamed: 0  bookId                                      title  \
0           0       1     Harry Potter and the Half-Blood Prince
1           1       2  Harry Potter and the Order of the Phoenix
2           2       3      Harry Potter and the Sorcerer's Stone
3           3       4    Harry Potter and the Chamber of Secrets
4           4       5   Harry Potter and the Prisoner of Azkaban

                       author           series  \
0                J.K. Rowling  Harry Potter #6
1  J.K. Rowling,Mary GrandPré  Harry Potter #5
2  J.K. Rowling,Mary GrandPré  Harry Potter #1
3                J.K. Rowling  Harry Potter #2
4  J.K. Rowling,Mary GrandPré  Harry Potter #3

                                         description  \
0  The war against Voldemort is not going well; e...
1  There is a door at the end of a silent corrido...
2  Harry Potter's life is miserable. His parents ...
3  The Dursleys were so mean and hideous that sum...
4  For twelve long years, the dread fortress of A...

                                              genres  \
0  Art,Biography,Business,Children's,Christian,Cl...
1  Art,Biography,Business,Children's,Christian,Cl...
2  Art,Biography,Business,Children's,Christian,Cl...
3  Art,Biography,Business,Children's,Christian,Cl...
4  Art,Biography,Business,Children's,Christian,Cl...

                                              awards  \
0  Locus Award Nominee for Best Young Adult Novel...
1  Bram Stoker Award for Works for Young Readers ...
2  Mythopoeic Fantasy Award for Children's Litera...
3  Mythopoeic Fantasy Award for Children's Litera...
4  Bram Stoker Award for Best Work for Young Read...

                                          characters  \
0  Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...
1  Sirius Black,Draco Malfoy,Ron Weasley,Petunia ...
2  Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...
3  Draco Malfoy,Ron Weasley,Petunia Dursley,Verno...
4  Sirius Black,Draco Malfoy,Ron Weasley,Petunia ...

                                              places  ...  \
0  Hogwarts School of Witchcraft and Wizardry,Eng...  ...
1  Hogwarts School of Witchcraft and Wizardry,Lon...  ...
2  London, England,Hogwarts School of Witchcraft ...  ...
3  Hogwarts School of Witchcraft and Wizardry,Hog...  ...
4  Hogwarts School of Witchcraft and Wizardry,Lon...  ...

          publish_date num_pages num_ratings num_reviews avg_rating   rated_1  \
0  September 16th 2006     652.0   2553909.0     41470.0       4.57   13147.0
1       September 2004     870.0   2631427.0     44793.0       4.50   16236.0
2    November 1st 2003     309.0   7434783.0    117823.0       4.48  126344.0
3    November 1st 2003     352.0   2878196.0     55839.0       4.43   15623.0
4         May 1st 2004     435.0   2972519.0     58483.0       4.57   14124.0

    rated_2   rated_3    rated_4    rated_5
0   29020.0  174312.0   608825.0  1728605.0
1   41738.0  231438.0   665628.0  1676387.0
2  147184.0  627803.0  1694206.0  4839246.0
3   55060.0  315917.0   787181.0  1704415.0
4   29105.0  214151.0   701765.0  2013374.0

[5 rows x 24 columns]
Descrizione categorie numeriche:

,Unnamed: 0,bookId,num_pages,num_ratings,num_reviews,avg_rating,rated_1,rated_2,rated_3,rated_4,rated_5
count,20068.000000,20068.000000,18428.000000,1.950900e+04,19509.000000,19509.000000,16638.000000,16638.000000,1.663800e+04,1.663800e+04,1.663800e+04
mean,10033.500000,9980.296990,292.454580,7.410352e+04,2073.157825,3.694199,2269.427575,4625.519654,1.570520e+04,2.780118e+04,3.648904e+04
std,5793.276937,5762.986523,307.325611,3.302812e+05,7394.394617,0.998125,10663.287509,18495.318026,5.798617e+04,1.062333e+05,1.774864e+05
min,0.000000,1.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,5016.750000,5014.750000,148.000000,2.000000e+01,2.000000,3.670000,1.000000,4.000000,1.700000e+01,2.600000e+01,2.400000e+01
50%,10033.500000,9937.500000,252.000000,4.370000e+02,32.000000,3.930000,17.000000,56.000000,2.420000e+02,3.800000e+02,3.560000e+02
75%,15050.250000,14968.250000,369.000000,1.114600e+04,567.000000,4.140000,323.750000,979.000000,3.945500e+03,6.686750e+03,6.131500e+03
max,20067.000000,20000.000000,23931.000000,7.444102e+06,117992.000000,5.000000,562807.000000,560978.000000,1.052619e+06,1.696235e+06,4.845445e+06

Descrizione categorie numeriche:

,title,author,series,description,genres,awards,characters,places,isbn,isbn13,language,first_publish_date,publish_date
count,19509,19507,4279,17381,19812,3129,4779,4040,17531,19210,17289,14591,19022
unique,16906,11937,2901,16321,9696,1639,2272,1117,17266,18926,22,3084,5050
top,The Lord of the Rings,Piers Anthony,Munch Bunch,This scarce antiquarian book is a facsimile re...,"Art,Biography,Business,Children's,Christian,Cl...",Hugo Award Nominee for Best All-Time Series 19...,"Jack Aubrey,Stephen Maturin",United States of America,0142000957,9780143058144,English,2006,2002
freq,25,94,32,53,4831,23,32,235,4,4,16321,276,101

                    Missing_Count  Missing_%
awards                      16939      84.41
places                      16028      79.87
series                      15789      78.68
characters                  15289      76.19
first_publish_date           5477      27.29
rated_5                      3430      17.09
rated_3                      3430      17.09
rated_2                      3430      17.09
rated_4                      3430      17.09
rated_1                      3430      17.09
language                     2779      13.85
description                  2687      13.39
isbn                         2537      12.64
num_pages                    1640       8.17
publish_date                 1046       5.21
isbn13                        858       4.28
author                        561       2.80
avg_rating                    559       2.79
num_ratings                   559       2.79
title                         559       2.79
num_reviews                   559       2.79
genres                        256       1.28
bookId                          0       0.00
Unnamed: 0                      0       0.00

 Valori mancanti: 101272 (504.64%)

In [8]:
arr_genres = df["genres"].dropna().str.split(",").explode().str.strip().to_numpy()

s_genres = set(arr_genres)

arr_authors = df["author"].dropna().str.split(",").explode().str.strip().to_numpy()

s_authors = set(arr_authors)

print(f'Generi unici: {len(s_genres)} \nAutori unici: {len(s_authors)}')

Generi unici: 842
Autori unici: 15255